name: update

on:
  push:
    branches: [main]

  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

  workflow_dispatch:  # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run script
        run: python run.py
      
      - name: Upload playlist
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build
          force_orphan: true
